version: '3'
services:
  app:
    image: aalwei/supportticketsystemoracle:latest
    build:
      context: ./
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@tcp://localhost:15216/ORCLCDB.localdomain   #in my case using docker toolbox on windows 11 home , my localhost is docker I machine :192.168.99.101
      - SPRING_DATASOURCE_USERNAME=sys as sysdba
      - SPRING_DATASOURCE_PASSWORD=Oradoc_db1
    depends_on:
      - db
    restart: on-failure
    networks:
      - oracle-network

  db:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    container_name: oracle-db
    environment:
      - ORACLE_SID=ORCL
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PASSWORD=Oradoc_db1
      - ORACLE_USER=sys as sysdba
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "15216:1521"  # Default Oracle DB port
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always
    networks:
      - oracle-network

volumes:
  oracle-data:
    driver: local

networks:
  oracle-network:
    driver: bridge