version: '3'

services:
  springboot-app:
    image: aalwei/supportticketsystemoracle:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@:1521/xe
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: admin

    depends_on:
      - oracle-db
    networks:
      - oracle


  oracle-db:
    image: gvenzl/oracle-xe:21
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=admin
      - ORACLE_DATABASE= xe
      - ORACLE_USER=admin
    networks:
      - oracle

networks:
  oracle:
    driver: bridge