version: '3'
services:
  app:
    #image: aalwei/supportticketsystem-mysql
    build:
      context: ./
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/localdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : localdb
      MYSQL_USER : admin
      MYSQL_PASSWORD: root

